### ISSUE TITLE
installation errors

### ISSUE THREAD

**Issue by bastianilso** [matthiasclasen/portal-test#5]
just following the instructions in README.md, seem to yield the following error with flatpak 0.9.1:
"error: GPG verification enabled, but no summary signatures found (use gpg-verify-summary=false in remote config to disable)"

maybe disabling gpg verification is a step that needs to be mentioned in the readme?

although, even after disabling it I also get:
"error: Remote listing for portal-test not available; server has no summary file
Check the URL passed to remote-add was valid"

not sure what is going on there.

**Comment by mariospr** [comment]
You need to run `flatpak remote-add --user --no-gpg-verify portal-test file:///path/to/repo` instead, or edit `~/.local/share/flatpak/repo/config` after installing this new repo and then making sure that you have this:
```
[remote "portal-test"]
gpg-verify=false
gpg-verify-summary=false
url=file:///home/mario/work/flatpak/portal-test/flatpak/repo
```

**Comment by mariospr** [comment]
Small PR here: https://github.com/matthiasclasen/portal-test/pull/6
